[build]
  functions = "functions/"
  publish = "/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "https://forum-wtchs.netlify.app/signup"
  status = 200