[build]
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
        Content-Security-Policy = """
        font-src https://fonts.gstatic.com/;
        manifest-src https://forum-wtchs.netlify.app/;
        connect-src https://db.fauna.com/ 'self';
        img-src 'self' https://firebasestorage.googleapis.com/;
        style-src 'self' https://fonts.googleapis.com/;
        script-src 'self';
        frame-ancestors 'none'; 
        default-src 'none';
        base-uri 'none';
        form-action 'self'; """
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        
