[build]
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
        Content-Security-Policy = """
        font-src https://fonts.gstatic.com;
        default-src 'none';
        connect-src 'self' https://db.fauna.com;
        img-src 'self' https://firebasestorage.googleapis.com;
        style-src 'self';
        script-src 'self';
        frame-ancestors 'none' """
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        
