[build]
  functions = "functions/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
        Content-Security-Policy = "script-src 'self';
        default-src 'none';
        font-src 'self';
        style-src 'self';
        frame-ancestors 'none'"
